services:
  mysql:
    image: mysql:8.0
    container_name: "mysql"
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TZ=$TZ
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    networks:
      - app

  app:
    build: .
    container_name: "spring_app"
    depends_on:
      - mysql
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
                  "spring.datasource.url" : "jdbc:mysql://mysql:$MYSQL_DOCKER_PORT/$MYSQL_DB",
                  "spring.datasource.username" : "$MYSQL_USER",
                  "spring.datasource.password" : "$MYSQL_PASSWORD",
                  "spring.jpa.hibernate.ddl-auto" : "validate"
                }'
      TZ: $TZ
    networks:
      - monitoring
      - app

networks:
  monitoring:
    driver: bridge
  app:
    driver: bridge
